words = {
    "animals": {"ant", "bear", "camel", "dolphin", "eagle", "fish", "giraffe", "hyena", "iguana", "jackal",
                "kangaroo", "lynx", "moose", "narwhal", "owl", "penguin", "racoon", "seagull", "tiger"},
    "archeology": {"karnak", "tyrannosaurus", "rosetta", "egypt", "babylon", "triassic", "mammoth", "australopithecus",
                   "acropolis", "aztecs", "assyrians", "tutankhamen", "velociraptor", "cretaceous", "alexandria",
                   "jurassic", "machu picchu", "sumerians", "pyramid", "imhotep"},
    "countries": {"greece", "sweden", "mexico", "zimbabwe", "turkey", "japan", "guatemala", "russia", "france", "spain",
                  "hungary", "tanzania", "romania", "gabon", "irak", "uruguay", "yemen", "bulgaria", "india"},
    "food": {"hamburguer", "spaghetti", "croissant", "stroganoff", "banana", "watermelon", "bread", "pizza", "beer",
             "sushi", "burrito", "wine", "chicken", "soup", "apple", "lettuce", "coconut", "baguette", "tomato"},
    "miscellaneous": {"house", "bedroom", "jupiter", "window", "soccer", "basketball", "stonehenge", "pensilvania",
                      "dwarf", "shower", "billiard", "sunshine", "eiffel", "baggage", "sword", "monalisa", "cookie"},
    "mithology": {"zeus", "pandora", "thor", "odin", "pantheon", "valhalla", "icarus", "appolo", "hercules", "vishnu",
                  "arachne", "minotaurus", "andromeda", "horus", "isis", "arturus", "poseidon", "bacco", "vulcanus"},
    "movies": {"schwarzenegger", "godfather", "stallone", "scarface", "tarantino", "hollywood", "dicaprio", "hepburn",
               "lebowsky", "nimoy", "skywalker", "spielberg", "eastwood", "orwell", "platoon", "carrey", "spartacus",
               "hitchcock", "zellwegger"},
    "objects": {"candle", "box", "shoe", "shirt", "bottle", "cellphone", "pencil", "plate", "stairs", "underwear",
                "fork", "shower", "fridge", "microwave", "notebook", "hammer", "hat", "sock", "dicionary"},
    "sports": {"footbal", "golf", "boxing", "volleyball", "basketball", "indianapolis", "olympics", "tyson", "canseco",
               "soccer", "baseball", "karate", "tennis", "dodgeball", "championship", "messi", "ronaldo", "schumacher",
               "jordan"},
    "technology": {"cellphone", "microwave", "satellite", "internet", "website", "google", "zuckeberg", "microsoft",
                   "iphone", "hubble", "voyager", "television", "instagram", "jobs", "musk", "tesla", "qrcode",
                   "bluetooth", "wireless"}
}