"""
MÓDULO 3
AULA 6
EXERCÍCIOS
1 - CRIAR UMA FUNÇÃO1 QUE RECEBA UMA FUNÇÃO2 COMO
PARÂMETRO E RETORNE O VALOR DA FUNÇÃO2 EXECUTADA

2 - CRIAR UMA FUNÇÃO1 QUE RECEBA UMA FUNÇÃO2 COMO
PARÂMETRO E RETORNE O VALOR DA FUNÇÃO2 EXECUTADA.
FAÇA A FUNÇÃO1 EXECUTAR DUAS FUNÇÕES QUE RECEBAM
UM NÚMERO DIFERENTE DE ARGUMENTOS.
"""

# 1
c = 0


